services:
    connect:
        image: quay.io/debezium/connect:3.3.1.Final
        hostname: connect
        container_name: connect
        ports:
            - "8083:8083"
        environment:
            BOOTSTRAP_SERVERS: "kafka1:29092,kafka2:29092,kafka3:29092"
            GROUP_ID: 1
            CONFIG_STORAGE_TOPIC: "my_connect_configs"
            OFFSET_STORAGE_TOPIC: "my_connect_offsets"
            STATUS_STORAGE_TOPIC: "my_connect_statuses"
            CONNECT_PLUGIN_PATH: /kafka/connect

            KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
            VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
            VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
            # KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
            # VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
            # VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
            
            # Enable environment variable config provider
            SQLSERVER_USER: ${SQLSERVER_USER}
            SQLSERVER_PASS: ${SQLSERVER_PASS}
            CONNECT_CONFIG_PROVIDERS: env
            CONNECT_CONFIG_PROVIDERS_ENV_CLASS: org.apache.kafka.common.config.provider.EnvVarConfigProvider
        env_file:
            - .env
        volumes:
            - ./connect-plugins:/kafka/connect
        depends_on:
            - kafka1
            - kafka2
            - kafka3
            - schema-registry
    kafka1:
        image: confluentinc/cp-kafka:8.1.0
        hostname: kafka1
        container_name: kafka1
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka1:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:29092,EXTERNAL://localhost:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093,3@kafka3:29093"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            # Replace CLUSTER_ID with a unique base64 UUID using "/usr/bin/kafka-storage random-uuid"
            CLUSTER_ID: "D3ewVMj_SQ6tkaZzJEIvzQ"
            KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    kafka2:
        image: confluentinc/cp-kafka:8.1.0
        hostname: kafka2
        container_name: kafka2
        ports:
            - "9093:9093"
        environment:
            KAFKA_NODE_ID: 2
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka2:29092,CONTROLLER://kafka2:29093,EXTERNAL://0.0.0.0:9093"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:29092,EXTERNAL://localhost:9093"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093,3@kafka3:29093"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            CLUSTER_ID: "D3ewVMj_SQ6tkaZzJEIvzQ"
            KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    kafka3:
        image: confluentinc/cp-kafka:8.1.0
        hostname: kafka3
        container_name: kafka3
        ports:
            - "9094:9094"
        environment:
            KAFKA_NODE_ID: 3
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka3:29092,CONTROLLER://kafka3:29093,EXTERNAL://0.0.0.0:9094"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka3:29092,EXTERNAL://localhost:9094"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093,3@kafka3:29093"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            CLUSTER_ID: "D3ewVMj_SQ6tkaZzJEIvzQ"
            KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    schema-registry:
        image: confluentinc/cp-schema-registry:8.1.0
        hostname: schema-registry
        container_name: schema-registry
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka1:29092,kafka2:29092,kafka3:29092"
            SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
        depends_on:
            - kafka1
            - kafka2
            - kafka3
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8080:8080"
        depends_on:
            - kafka1
            - kafka2
            - kafka3
            - schema-registry
            - connect
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:29092,kafka2:29092,kafka3:29092"
            KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
            KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
            KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
            DYNAMIC_CONFIG_ENABLED: "true"           
networks:
  default:
    name: my-network
    external: true