bootstrap_servers: kafka:9092
topic_prefix: olist.oltp
checkpoint_base: s3a://olist-ecommerce/checkpoints
topic_suffix:
  - customers
  - order_items
  - order_payments
  - order_reviews
  - orders
  - products
  - sellers