jobs:
  raw_ingestion: olist-raw-ingestion
  init_lakehouse: olist-init-lakehouse
  bronze_cdc_ddl: olist-bronze-cdc-ddl
  bronze_cdc_ingestion_backfill: olist-bronze-cdc-ingestion-backfill
  bronze_cdc_ingestion_append: olist-bronze-cdc-ingestion-append
  bronze_lookup_ddl_ingestion: olist-bronze-lookup-ddl-ingestion
  silver: olist-silver
  gold_customers: olist-gold-customers
  gold_sellers: olist-gold-sellers
  gold_products: olist-gold-products
  gold_date: olist-gold-date
  gold_dims_bootstrap: olist-gold-dims-bootstrap
  gold_orders: olist-gold-orders
  gold_order_items: olist-gold-order-items
  gold_order_payments: olist-gold-order-payments
  gold_order_reviews: olist-gold-order-reviews